-- target("MSIS90")
--     set_kind("static")
--     add_files("msise90_sub.for")
-- 
--     set_toolchains("ifort")     -- don't use gfortran
--     add_fcflags("/Qautodouble")  -- set REAL to double by default
--     add_fcflags("/auto")  -- do not generate static vars in subroutings
--     --add_fcflags("/Qauto-scalar")
--     add_fcflags("/zero")  -- init with zero

-- add_requires("libf2c")
-- target("MSIS90")
--     set_kind("static")
-- 
--     add_packages("libf2c")
--     add_files("msise90_sub.c")