---
exclude_paths:
  - "docs/**"
  - "examples/**"
  - "test/**"
  - "thirdparty/**"
  - "src/AstCore/Propagator/SGP4/Vallado/**"
  - "src/AstWeather/Atmosphere/DTM_12/**"
  # HarrisPriester 模型不是第三方代码
  # - "src/AstWeather/Atmosphere/HarrisPriester/**"
  - "src/AstWeather/Atmosphere/JacchiaRoberts/**"
  - "src/AstWeather/Atmosphere/Jacchi-Reference-Atmosphere/**"
  - "src/AstWeather/Atmosphere/MSIS_Vers/**"
  - "src/AstWeather/Atmosphere/MSIS86/**"
  - "src/AstWeather/Atmosphere/MSIS90/**"
  - "src/AstWeather/Atmosphere/NRLMSIS00/**"
  - "src/AstWeather/Atmosphere/nrlmsise-00/**"
  # ussa1976 模型里的cpp文件不是第三方代码
  #- "src/AstWeather/Atmosphere/ussa1976/**"
  - "src/AstWeather/Magnetosphere/aep8/**"
  - "src/AstWeather/Magnetosphere/igrf/**"
  - "src/AstWeather/Magnetosphere/IGRF13/**"