target("AstUiUtil")
    add_rules("ast.qt.shared")
    set_kind("shared")
    add_files("**.cpp")
    add_files("**.hpp")
    add_headerfiles("**.hpp", {prefixdir="AstUiPilot"})
    add_deps("AstAI", "AstUtil")
    add_defines("AST_BUILD_LIB_UIUTIL")
    set_default(false)

