target("AstUtil")
    set_kind("shared")
    add_files("**.cpp")
    add_files("**.cxx")
    add_headerfiles("**.hpp", {prefixdir="AstUtil"})
    add_headerfiles("**.h", {prefixdir="AstUtil"})
    add_headerfiles("../../include/AstGlobal.h")
    add_headerfiles("../../include/AstCompiler.h")
    add_defines("AST_BUILD_LIB_UTIL")
    -- add_extrafiles("xmake.lua")    
