// AstUiAI 工程聚合头文件
#include "AstUiAI/AstUiAIGlobal.hpp"
#include "AstUiAI/UiChatDockWidget.hpp"
#include "AstUiAI/UiChatEventHandler.hpp"
#include "AstUiAI/UiChatInput.hpp"
#include "AstUiAI/UiChatMainWidget.hpp"
#include "AstUiAI/UiChatMessageItem.hpp"
#include "AstUiAI/UiChatMessageList.hpp"
#include "AstUiAI/UiChatPanel.hpp"
#include "AstUiAI/UiChatWorker.hpp"
#include "AstUiAI/UiToolCallCard.hpp"
#include "AstUiAI/UiToolCallTimeline.hpp"
