// AstWeather 工程聚合头文件
#include "AstWeather/AstWeatherGlobal.h"
#include "AstWeather/Atmosphere.hpp"
#include "AstWeather/Debris.hpp"
#include "AstWeather/GeomagneticIndex.hpp"
#include "AstWeather/MSIS_Vers.h"
#include "AstWeather/Magnetosphere.hpp"
#include "AstWeather/aep8.hpp"
#include "AstWeather/atmos76.h"
#include "AstWeather/atmos76.hpp"
#include "AstWeather/atmosapi.h"
#include "AstWeather/igrf.hpp"
#include "AstWeather/nrlmsise-00.h"
#include "AstWeather/nrlmsise-00.hpp"
#include "AstWeather/val_always.h"
#include "AstWeather/val_atm_jr.h"
