// AstWeather 工程聚合头文件
#include "AstWeather/AstWeatherGlobal.h"
#include "AstWeather/Atmosphere.hpp"
#include "AstWeather/Debris.hpp"
#include "AstWeather/Magnetosphere.hpp"
#include "AstWeather/aep8.hpp"
#include "AstWeather/atmos76.h"
#include "AstWeather/atmosapi.h"
#include "AstWeather/igrf.hpp"
#include "AstWeather/nrlmsise-00.h"
#include "AstWeather/nrlmsise-00.hpp"
