#pragma once
#include "AstCore/InertialFrame.hpp"
#include "AstCore/LocalOrbitFrame.hpp"
#include "AstCore/LocalHorizonalFrame.hpp"
#include "AstCore/MoonFrame.hpp"
#include "AstCore/EarthFrame.hpp"
#include "AstCore/PlanetFrame.hpp"
#include "AstCore/BuiltinAxes.hpp"
#include "AstCore/BuiltinFrame.hpp"
