target("AstDataUpdate")
    set_kind("shared")
    add_files("**.cpp")
    add_headerfiles("**.hpp", {prefixdir="AstDataUpdate"})
    add_headerfiles("**.h", {prefixdir="AstDataUpdate"})
    add_deps("AstUtil", "AstCore")
    add_defines("AST_BUILD_LIB_DATAUPDATE")
    set_default(false)
