<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="zh_CN">
<context>
    <name>AdvCAT</name>
    <message>
        <source>AdvCAT</source>
        <translation>高级接近分析</translation>
    </message>
</context>
<context>
    <name>Aircraft</name>
    <message>
        <source>Aircraft</source>
        <translation>航空器</translation>
    </message>
</context>
<context>
    <name>Antenna</name>
    <message>
        <source>Antenna</source>
        <translation>天线</translation>
    </message>
</context>
<context>
    <name>AreaTarget</name>
    <message>
        <source>AreaTarget</source>
        <translation>区域目标</translation>
    </message>
</context>
<context>
    <name>Asteroid</name>
    <message>
        <source>Asteroid</source>
        <translation>小行星</translation>
    </message>
</context>
<context>
    <name>AttitudeCoverage</name>
    <message>
        <source>AttitudeCoverage</source>
        <translation>姿态覆盖</translation>
    </message>
</context>
<context>
    <name>AttitudeFigureOfMerit</name>
    <message>
        <source>AttitudeFigureOfMerit</source>
        <translation>姿态品质因数</translation>
    </message>
</context>
<context>
    <name>Axes</name>
    <message>
        <source>Axes</source>
        <translation>坐标轴</translation>
    </message>
</context>
<context>
    <name>AxesLinkTo</name>
    <message>
        <source>AxesLinkTo</source>
        <translation>关联坐标轴</translation>
    </message>
</context>
<context>
    <name>BodyAttraction</name>
    <message>
        <source>BodyAttraction</source>
        <translation>天体引力</translation>
    </message>
</context>
<context>
    <name>BodyEphemerisDE</name>
    <message>
        <source>BodyEphemerisDE</source>
        <translation>天体星历(DE)</translation>
    </message>
</context>
<context>
    <name>BodyEphemerisNoop</name>
    <message>
        <source>BodyEphemerisNoop</source>
        <translation>天体星历(空)</translation>
    </message>
</context>
<context>
    <name>BodyEphemerisSPK</name>
    <message>
        <source>BodyEphemerisSPK</source>
        <translation>天体星历(SPK)</translation>
    </message>
</context>
<context>
    <name>BodyOrientation</name>
    <message>
        <source>BodyOrientation</source>
        <translation>天体指向</translation>
    </message>
</context>
<context>
    <name>BodyShape</name>
    <message>
        <source>BodyShape</source>
        <translation>天体形状</translation>
    </message>
</context>
<context>
    <name>Burn</name>
    <message>
        <source>Burn</source>
        <translation>推力</translation>
    </message>
</context>
<context>
    <name>BurnImpulsive</name>
    <message>
        <source>BurnImpulsive</source>
        <translation>脉冲推力</translation>
    </message>
</context>
<context>
    <name>CelestialBody</name>
    <message>
        <source>SolarSystemBarycenter</source>
        <translation>太阳系质心</translation>
    </message>
    <message>
        <source>EarthMoonBarycenter</source>
        <translation>地月质心</translation>
    </message>
    <message>
        <source>Mercury</source>
        <translation>水星</translation>
    </message>
    <message>
        <source>Venus</source>
        <translation>金星</translation>
    </message>
    <message>
        <source>Earth</source>
        <translation>地球</translation>
    </message>
    <message>
        <source>Mars</source>
        <translation>火星</translation>
    </message>
    <message>
        <source>Jupiter</source>
        <translation>木星</translation>
    </message>
    <message>
        <source>Saturn</source>
        <translation>土星</translation>
    </message>
    <message>
        <source>Uranus</source>
        <translation>天王星</translation>
    </message>
    <message>
        <source>Neptune</source>
        <translation>海王星</translation>
    </message>
    <message>
        <source>Pluto</source>
        <translation>冥王星</translation>
    </message>
    <message>
        <source>Moon</source>
        <translation>月球</translation>
    </message>
    <message>
        <source>Sun</source>
        <translation>太阳</translation>
    </message>
    <message>
        <source>Phobos</source>
        <translation>火卫一</translation>
    </message>
    <message>
        <source>Deimos</source>
        <translation>火卫二</translation>
    </message>
    <message>
        <source>Io</source>
        <translation>木卫一</translation>
    </message>
    <message>
        <source>Europa</source>
        <translation>木卫二</translation>
    </message>
    <message>
        <source>Ganymede</source>
        <translation>木卫三</translation>
    </message>
    <message>
        <source>Callisto</source>
        <translation>木卫四</translation>
    </message>
    <message>
        <source>Amalthea</source>
        <translation>木卫五</translation>
    </message>
    <message>
        <source>Himalia</source>
        <translation>木卫六</translation>
    </message>
    <message>
        <source>Elara</source>
        <translation>木卫七</translation>
    </message>
    <message>
        <source>Pasiphae</source>
        <translation>木卫八</translation>
    </message>
    <message>
        <source>Sinope</source>
        <translation>木卫九</translation>
    </message>
    <message>
        <source>Lysithea</source>
        <translation>木卫十</translation>
    </message>
    <message>
        <source>Carme</source>
        <translation>木卫十一</translation>
    </message>
    <message>
        <source>Ananke</source>
        <translation>木卫十二</translation>
    </message>
    <message>
        <source>Leda</source>
        <translation>木卫十三</translation>
    </message>
    <message>
        <source>Thebe</source>
        <translation>木卫十四</translation>
    </message>
    <message>
        <source>Adrastea</source>
        <translation>木卫十五</translation>
    </message>
    <message>
        <source>Metis</source>
        <translation>木卫十六</translation>
    </message>
    <message>
        <source>Mimas</source>
        <translation>土卫一</translation>
    </message>
    <message>
        <source>Enceladus</source>
        <translation>土卫二</translation>
    </message>
    <message>
        <source>Tethys</source>
        <translation>土卫三</translation>
    </message>
    <message>
        <source>Dione</source>
        <translation>土卫四</translation>
    </message>
    <message>
        <source>Rhea</source>
        <translation>土卫五</translation>
    </message>
    <message>
        <source>Titan</source>
        <translation>土卫六</translation>
    </message>
    <message>
        <source>Hyperion</source>
        <translation>土卫七</translation>
    </message>
    <message>
        <source>Iapetus</source>
        <translation>土卫八</translation>
    </message>
    <message>
        <source>Phoebe</source>
        <translation>土卫九</translation>
    </message>
    <message>
        <source>Janus</source>
        <translation>土卫十</translation>
    </message>
    <message>
        <source>Epimetheus</source>
        <translation>土卫十一</translation>
    </message>
    <message>
        <source>Helene</source>
        <translation>土卫十二</translation>
    </message>
    <message>
        <source>Telesto</source>
        <translation>土卫十三</translation>
    </message>
    <message>
        <source>Calypso</source>
        <translation>土卫十四</translation>
    </message>
    <message>
        <source>Atlas</source>
        <translation>土卫十五</translation>
    </message>
    <message>
        <source>Prometheus</source>
        <translation>土卫十六</translation>
    </message>
    <message>
        <source>Pandora</source>
        <translation>土卫十七</translation>
    </message>
    <message>
        <source>Pan</source>
        <translation>土卫十八</translation>
    </message>
    <message>
        <source>Methone</source>
        <translation>土卫三十二</translation>
    </message>
    <message>
        <source>Pallene</source>
        <translation>土卫三十三</translation>
    </message>
    <message>
        <source>Polydeuces</source>
        <translation>土卫三十四</translation>
    </message>
    <message>
        <source>Daphnis</source>
        <translation>土卫三十五</translation>
    </message>
    <message>
        <source>Anthe</source>
        <translation>土卫四十九</translation>
    </message>
    <message>
        <source>Aegaeon</source>
        <translation>土卫五十三</translation>
    </message>
    <message>
        <source>Ariel</source>
        <translation>天卫一</translation>
    </message>
    <message>
        <source>Umbriel</source>
        <translation>天卫二</translation>
    </message>
    <message>
        <source>Titania</source>
        <translation>天卫三</translation>
    </message>
    <message>
        <source>Oberon</source>
        <translation>天卫四</translation>
    </message>
    <message>
        <source>Miranda</source>
        <translation>天卫五</translation>
    </message>
    <message>
        <source>Cordelia</source>
        <translation>天卫六</translation>
    </message>
    <message>
        <source>Ophelia</source>
        <translation>天卫七</translation>
    </message>
    <message>
        <source>Bianca</source>
        <translation>天卫八</translation>
    </message>
    <message>
        <source>Cressida</source>
        <translation>天卫九</translation>
    </message>
    <message>
        <source>Desdemona</source>
        <translation>天卫十</translation>
    </message>
    <message>
        <source>Juliet</source>
        <translation>天卫十一</translation>
    </message>
    <message>
        <source>Portia</source>
        <translation>天卫十二</translation>
    </message>
    <message>
        <source>Rosalind</source>
        <translation>天卫十三</translation>
    </message>
    <message>
        <source>Belinda</source>
        <translation>天卫十四</translation>
    </message>
    <message>
        <source>Puck</source>
        <translation>天卫十五</translation>
    </message>
    <message>
        <source>Triton</source>
        <translation>海卫一</translation>
    </message>
    <message>
        <source>Nereid</source>
        <translation>海卫二</translation>
    </message>
    <message>
        <source>Naiad</source>
        <translation>海卫三</translation>
    </message>
    <message>
        <source>Thalassa</source>
        <translation>海卫四</translation>
    </message>
    <message>
        <source>Despina</source>
        <translation>海卫五</translation>
    </message>
    <message>
        <source>Galatea</source>
        <translation>海卫六</translation>
    </message>
    <message>
        <source>Larissa</source>
        <translation>海卫七</translation>
    </message>
    <message>
        <source>Proteus</source>
        <translation>海卫八</translation>
    </message>
    <message>
        <source>Charon</source>
        <translation>冥卫一</translation>
    </message>
    <message>
        <source>MercuryBarycenter</source>
        <translation>水星系质心</translation>
    </message>
    <message>
        <source>VenusBarycenter</source>
        <translation>金星系质心</translation>
    </message>
    <message>
        <source>MarsBarycenter</source>
        <translation>火星系质心</translation>
    </message>
    <message>
        <source>JupiterBarycenter</source>
        <translation>木星系质心</translation>
    </message>
    <message>
        <source>SaturnBarycenter</source>
        <translation>土星系质心</translation>
    </message>
    <message>
        <source>UranusBarycenter</source>
        <translation>天王星系质心</translation>
    </message>
    <message>
        <source>NeptuneBarycenter</source>
        <translation>海王星系质心</translation>
    </message>
    <message>
        <source>PlutoBarycenter</source>
        <translation>冥王星系质心</translation>
    </message>
    <message>
        <source>CelestialBody</source>
        <translation>天体</translation>
    </message>
</context>
<context>
    <name>Chain</name>
    <message>
        <source>Chain</source>
        <translation>链</translation>
    </message>
</context>
<context>
    <name>CommSystem</name>
    <message>
        <source>CommSystem</source>
        <translation>通信系统</translation>
    </message>
</context>
<context>
    <name>Command</name>
    <message>
        <source>Command</source>
        <translation>命令</translation>
    </message>
</context>
<context>
    <name>Constellation</name>
    <message>
        <source>Constellation</source>
        <translation>星座</translation>
    </message>
</context>
<context>
    <name>CoverageDefinition</name>
    <message>
        <source>CoverageDefinition</source>
        <translation>覆盖定义</translation>
    </message>
</context>
<context>
    <name>DetectorAccess</name>
    <message>
        <source>DetectorAccess</source>
        <translation>访问检测器</translation>
    </message>
</context>
<context>
    <name>DetectorAltitude</name>
    <message>
        <source>DetectorAltitude</source>
        <translation>高度检测器</translation>
    </message>
</context>
<context>
    <name>DetectorAlwaysTripped</name>
    <message>
        <source>DetectorAlwaysTripped</source>
        <translation>常通检测器</translation>
    </message>
</context>
<context>
    <name>DetectorApoapsis</name>
    <message>
        <source>DetectorApoapsis</source>
        <translation>远心点检测器</translation>
    </message>
</context>
<context>
    <name>DetectorAscendingNode</name>
    <message>
        <source>DetectorAscendingNode</source>
        <translation>升交点检测器</translation>
    </message>
</context>
<context>
    <name>DetectorBodyRelated</name>
    <message>
        <source>DetectorBodyRelated</source>
        <translation>天体相关检测器</translation>
    </message>
</context>
<context>
    <name>DetectorCartesian</name>
    <message>
        <source>DetectorCartesian</source>
        <translation>笛卡尔坐标检测器</translation>
    </message>
</context>
<context>
    <name>DetectorDeltaV</name>
    <message>
        <source>DetectorDeltaV</source>
        <translation>速度增量检测器</translation>
    </message>
</context>
<context>
    <name>DetectorDescendingNode</name>
    <message>
        <source>DetectorDescendingNode</source>
        <translation>降交点检测器</translation>
    </message>
</context>
<context>
    <name>DetectorDuration</name>
    <message>
        <source>DetectorDuration</source>
        <translation>持续时间检测器</translation>
    </message>
</context>
<context>
    <name>DetectorEpoch</name>
    <message>
        <source>DetectorEpoch</source>
        <translation>历元检测器</translation>
    </message>
</context>
<context>
    <name>DetectorFrameRelated</name>
    <message>
        <source>DetectorFrameRelated</source>
        <translation>坐标系相关检测器</translation>
    </message>
</context>
<context>
    <name>DetectorLighting</name>
    <message>
        <source>DetectorLighting</source>
        <translation>光照检测器</translation>
    </message>
</context>
<context>
    <name>DetectorMeanAnomaly</name>
    <message>
        <source>DetectorMeanAnomaly</source>
        <translation>平近点角检测器</translation>
    </message>
</context>
<context>
    <name>DetectorPeriapsis</name>
    <message>
        <source>DetectorPeriapsis</source>
        <translation>近心点检测器</translation>
    </message>
</context>
<context>
    <name>DetectorPointRelated</name>
    <message>
        <source>DetectorPointRelated</source>
        <translation>点相关检测器</translation>
    </message>
</context>
<context>
    <name>DetectorRMagnitude</name>
    <message>
        <source>DetectorRMagnitude</source>
        <translation>相对距离检测器</translation>
    </message>
</context>
<context>
    <name>DetectorTrueAnomaly</name>
    <message>
        <source>DetectorTrueAnomaly</source>
        <translation>真近点角检测器</translation>
    </message>
</context>
<context>
    <name>DetectorUserSelect</name>
    <message>
        <source>DetectorUserSelect</source>
        <translation>用户选择检测器</translation>
    </message>
</context>
<context>
    <name>DetectorXYPlaneCross</name>
    <message>
        <source>DetectorXYPlaneCross</source>
        <translation>XY平面穿越检测器</translation>
    </message>
</context>
<context>
    <name>DetectorYZPlaneCross</name>
    <message>
        <source>DetectorYZPlaneCross</source>
        <translation>YZ平面穿越检测器</translation>
    </message>
</context>
<context>
    <name>DetectorZXPlaneCross</name>
    <message>
        <source>DetectorZXPlaneCross</source>
        <translation>ZX平面穿越检测器</translation>
    </message>
</context>
<context>
    <name>DifferentialCorrectorProfile</name>
    <message>
        <source>DifferentialCorrectorProfile</source>
        <translation>微分修正配置</translation>
    </message>
</context>
<context>
    <name>DragForce</name>
    <message>
        <source>DragForce</source>
        <translation>大气阻力</translation>
    </message>
</context>
<context>
    <name>EarthOrientation</name>
    <message>
        <source>EarthOrientation</source>
        <translation>地球指向参数</translation>
    </message>
</context>
<context>
    <name>EllipsoidShape</name>
    <message>
        <source>EllipsoidShape</source>
        <translation>椭球形状</translation>
    </message>
</context>
<context>
    <name>End</name>
    <message>
        <source>End</source>
        <translation>结束</translation>
    </message>
</context>
<context>
    <name>EventDetector</name>
    <message>
        <source>EventDetector</source>
        <translation>事件检测器</translation>
    </message>
</context>
<context>
    <name>EventTime</name>
    <message>
        <source>EventTime</source>
        <translation>事件时间</translation>
    </message>
</context>
<context>
    <name>EventTimeExplicit</name>
    <message>
        <source>EventTimeExplicit</source>
        <translation>显式事件时间</translation>
    </message>
</context>
<context>
    <name>Facility</name>
    <message>
        <source>Facility</source>
        <translation>设施</translation>
    </message>
</context>
<context>
    <name>FigureOfMerit</name>
    <message>
        <source>FigureOfMerit</source>
        <translation>品质因数</translation>
    </message>
</context>
<context>
    <name>ForceModel</name>
    <message>
        <source>ForceModel</source>
        <translation>力模型</translation>
    </message>
</context>
<context>
    <name>Frame</name>
    <message>
        <source>Frame</source>
        <translation>坐标系</translation>
    </message>
</context>
<context>
    <name>FrameAssembly</name>
    <message>
        <source>FrameAssembly</source>
        <translation>组合坐标系</translation>
    </message>
</context>
<context>
    <name>GravityForce</name>
    <message>
        <source>GravityForce</source>
        <translation>地球重力</translation>
    </message>
</context>
<context>
    <name>GroundVehicle</name>
    <message>
        <source>GroundVehicle</source>
        <translation>地面车辆</translation>
    </message>
</context>
<context>
    <name>HPOP</name>
    <message>
        <source>HPOP</source>
        <translation>高精度轨道预报器</translation>
    </message>
</context>
<context>
    <name>HPOPForceModel</name>
    <message>
        <source>HPOPForceModel</source>
        <translation>HPOP力模型</translation>
    </message>
</context>
<context>
    <name>InitialState</name>
    <message>
        <source>InitialState</source>
        <translation>初始状态</translation>
    </message>
</context>
<context>
    <name>LandingSite</name>
    <message>
        <source>LandingSite</source>
        <translation>着陆点</translation>
    </message>
</context>
<context>
    <name>LandingSiteCalcSunAzimuth</name>
    <message>
        <source>LandingSiteCalcSunAzimuth</source>
        <translation>着陆点太阳方位角计算</translation>
    </message>
</context>
<context>
    <name>LandingSiteCalcSunElevation</name>
    <message>
        <source>LandingSiteCalcSunElevation</source>
        <translation>着陆点太阳高度角计算</translation>
    </message>
</context>
<context>
    <name>LandingSiteCalculation</name>
    <message>
        <source>LandingSiteCalculation</source>
        <translation>着陆点计算</translation>
    </message>
</context>
<context>
    <name>LaunchVehicle</name>
    <message>
        <source>LaunchVehicle</source>
        <translation>运载火箭</translation>
    </message>
</context>
<context>
    <name>LineTarget</name>
    <message>
        <source>LineTarget</source>
        <translation>线目标</translation>
    </message>
</context>
<context>
    <name>MTO</name>
    <message>
        <source>MTO</source>
        <translation>多轨迹目标</translation>
    </message>
</context>
<context>
    <name>MainSequence</name>
    <message>
        <source>MainSequence</source>
        <translation>主序列</translation>
    </message>
</context>
<context>
    <name>Maneuver</name>
    <message>
        <source>Maneuver</source>
        <translation>机动</translation>
    </message>
</context>
<context>
    <name>Missile</name>
    <message>
        <source>Missile</source>
        <translation>导弹</translation>
    </message>
</context>
<context>
    <name>MoonOrientation</name>
    <message>
        <source>MoonOrientation</source>
        <translation>月球指向</translation>
    </message>
</context>
<context>
    <name>MotionBallistic</name>
    <message>
        <source>MotionBallistic</source>
        <translation>弹道运动</translation>
    </message>
</context>
<context>
    <name>MotionJ2Analytical</name>
    <message>
        <source>MotionJ2Analytical</source>
        <translation>J2解析运动</translation>
    </message>
</context>
<context>
    <name>MotionJ4Analytical</name>
    <message>
        <source>MotionJ4Analytical</source>
        <translation>J4解析运动</translation>
    </message>
</context>
<context>
    <name>MotionMissionCommand</name>
    <message>
        <source>MotionMissionCommand</source>
        <translation>任务指令运动</translation>
    </message>
</context>
<context>
    <name>MotionOrbitDynamics</name>
    <message>
        <source>MotionOrbitDynamics</source>
        <translation>轨道动力学运动</translation>
    </message>
</context>
<context>
    <name>MotionProfile</name>
    <message>
        <source>MotionProfile</source>
        <translation>运动配置</translation>
    </message>
</context>
<context>
    <name>MotionSimpleAscent</name>
    <message>
        <source>MotionSimpleAscent</source>
        <translation>简单上升运动</translation>
    </message>
</context>
<context>
    <name>MotionTwoBody</name>
    <message>
        <source>MotionTwoBody</source>
        <translation>二体运动</translation>
    </message>
</context>
<context>
    <name>Mover</name>
    <message>
        <source>Mover</source>
        <translation>运动体</translation>
    </message>
</context>
<context>
    <name>Place</name>
    <message>
        <source>Place</source>
        <translation>地点</translation>
    </message>
</context>
<context>
    <name>Planet</name>
    <message>
        <source>Planet</source>
        <translation>行星</translation>
    </message>
</context>
<context>
    <name>Point</name>
    <message>
        <source>Point</source>
        <translation>点</translation>
    </message>
</context>
<context>
    <name>PointMassForce</name>
    <message>
        <source>PointMassForce</source>
        <translation>质点引力</translation>
    </message>
</context>
<context>
    <name>Propagate</name>
    <message>
        <source>Propagate</source>
        <translation>轨道预报</translation>
    </message>
</context>
<context>
    <name>Radar</name>
    <message>
        <source>Radar</source>
        <translation>雷达</translation>
    </message>
</context>
<context>
    <name>Receiver</name>
    <message>
        <source>Receiver</source>
        <translation>接收器</translation>
    </message>
</context>
<context>
    <name>RelativityCorrection</name>
    <message>
        <source>RelativityCorrection</source>
        <translation>相对论修正</translation>
    </message>
</context>
<context>
    <name>Return</name>
    <message>
        <source>Return</source>
        <translation>返回</translation>
    </message>
</context>
<context>
    <name>RotationalData</name>
    <message>
        <source>RotationalData</source>
        <translation>旋转数据</translation>
    </message>
</context>
<context>
    <name>Satellite</name>
    <message>
        <source>Satellite</source>
        <translation>卫星</translation>
    </message>
</context>
<context>
    <name>ScStateCalcBodyRelated</name>
    <message>
        <source>ScStateCalcBodyRelated</source>
        <translation>航天器状态天体相关计算</translation>
    </message>
</context>
<context>
    <name>ScStateCalcDifference</name>
    <message>
        <source>ScStateCalcDifference</source>
        <translation>航天器状态差计算</translation>
    </message>
</context>
<context>
    <name>ScStateCalcEccentricity</name>
    <message>
        <source>ScStateCalcEccentricity</source>
        <translation>航天器状态偏心率计算</translation>
    </message>
</context>
<context>
    <name>ScStateCalcFrameRelated</name>
    <message>
        <source>ScStateCalcFrameRelated</source>
        <translation>航天器状态坐标系相关计算</translation>
    </message>
</context>
<context>
    <name>ScStateCalcPointRelated</name>
    <message>
        <source>ScStateCalcPointRelated</source>
        <translation>航天器状态点相关计算</translation>
    </message>
</context>
<context>
    <name>ScStateCalculation</name>
    <message>
        <source>ScStateCalculation</source>
        <translation>航天器状态计算</translation>
    </message>
</context>
<context>
    <name>Scenario</name>
    <message>
        <source>Scenario</source>
        <translation>场景</translation>
    </message>
</context>
<context>
    <name>ScriptingToolProfile</name>
    <message>
        <source>ScriptingToolProfile</source>
        <translation>脚本工具配置</translation>
    </message>
</context>
<context>
    <name>Segment</name>
    <message>
        <source>Segment</source>
        <translation>段</translation>
    </message>
</context>
<context>
    <name>SegmentCalculation</name>
    <message>
        <source>SegmentCalculation</source>
        <translation>段计算</translation>
    </message>
</context>
<context>
    <name>SegmentGraph</name>
    <message>
        <source>SegmentGraph</source>
        <translation>段图</translation>
    </message>
</context>
<context>
    <name>Sensor</name>
    <message>
        <source>Sensor</source>
        <translation>传感器</translation>
    </message>
</context>
<context>
    <name>Sequence</name>
    <message>
        <source>Sequence</source>
        <translation>任务序列</translation>
    </message>
</context>
<context>
    <name>Ship</name>
    <message>
        <source>Ship</source>
        <translation>舰船</translation>
    </message>
</context>
<context>
    <name>ShooterControl</name>
    <message>
        <source>ShooterControl</source>
        <translation>打靶控制量</translation>
    </message>
</context>
<context>
    <name>ShooterResult</name>
    <message>
        <source>ShooterResult</source>
        <translation>打靶结果</translation>
    </message>
</context>
<context>
    <name>SolarRadiationPressure</name>
    <message>
        <source>SolarRadiationPressure</source>
        <translation>太阳光压</translation>
    </message>
</context>
<context>
    <name>SolarSystem</name>
    <message>
        <source>SolarSystem</source>
        <translation>太阳系</translation>
    </message>
</context>
<context>
    <name>SpaceObject</name>
    <message>
        <source>SpaceObject</source>
        <translation>空间物体</translation>
    </message>
</context>
<context>
    <name>Spacecraft</name>
    <message>
        <source>Spacecraft</source>
        <translation>航天器</translation>
    </message>
</context>
<context>
    <name>SpacecraftState</name>
    <message>
        <source>SpacecraftState</source>
        <translation>航天器状态</translation>
    </message>
</context>
<context>
    <name>SphereShape</name>
    <message>
        <source>SphereShape</source>
        <translation>球形状</translation>
    </message>
</context>
<context>
    <name>SpheroidShape</name>
    <message>
        <source>SpheroidShape</source>
        <translation>旋转椭球形状</translation>
    </message>
</context>
<context>
    <name>Star</name>
    <message>
        <source>Star</source>
        <translation>恒星</translation>
    </message>
</context>
<context>
    <name>State</name>
    <message>
        <source>State</source>
        <translation>状态</translation>
    </message>
</context>
<context>
    <name>StateCartesian</name>
    <message>
        <source>StateCartesian</source>
        <translation>笛卡尔状态</translation>
    </message>
</context>
<context>
    <name>StateKeplerian</name>
    <message>
        <source>StateKeplerian</source>
        <translation>开普勒状态</translation>
    </message>
</context>
<context>
    <name>Stop</name>
    <message>
        <source>Stop</source>
        <translation>停止</translation>
    </message>
</context>
<context>
    <name>Submarine</name>
    <message>
        <source>Submarine</source>
        <translation>潜艇</translation>
    </message>
</context>
<context>
    <name>Target</name>
    <message>
        <source>Target</source>
        <translation>目标</translation>
    </message>
</context>
<context>
    <name>TargeterProfile</name>
    <message>
        <source>TargeterProfile</source>
        <translation>打靶配置</translation>
    </message>
</context>
<context>
    <name>TargeterSequence</name>
    <message>
        <source>TargeterSequence</source>
        <translation>打靶序列</translation>
    </message>
</context>
<context>
    <name>ThirdBodyForce</name>
    <message>
        <source>ThirdBodyForce</source>
        <translation>三体引力</translation>
    </message>
</context>
<context>
    <name>Transmitter</name>
    <message>
        <source>Transmitter</source>
        <translation>发射机</translation>
    </message>
</context>
<context>
    <name>Volumetric</name>
    <message>
        <source>Volumetric</source>
        <translation>体积对象</translation>
    </message>
</context>
</TS>
