<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="zh_CN">
<context>
    <name>CelestialBody</name>
    <message>
        <source>SolarSystemBarycenter</source>
        <translation>太阳系质心</translation>
    </message>
    <message>
        <source>EarthMoonBarycenter</source>
        <translation>地月质心</translation>
    </message>
    <message>
        <source>Mercury</source>
        <translation>水星</translation>
    </message>
    <message>
        <source>Venus</source>
        <translation>金星</translation>
    </message>
    <message>
        <source>Earth</source>
        <translation>地球</translation>
    </message>
    <message>
        <source>Mars</source>
        <translation>火星</translation>
    </message>
    <message>
        <source>Jupiter</source>
        <translation>木星</translation>
    </message>
    <message>
        <source>Saturn</source>
        <translation>土星</translation>
    </message>
    <message>
        <source>Uranus</source>
        <translation>天王星</translation>
    </message>
    <message>
        <source>Neptune</source>
        <translation>海王星</translation>
    </message>
    <message>
        <source>Pluto</source>
        <translation>冥王星</translation>
    </message>
    <message>
        <source>Moon</source>
        <translation>月球</translation>
    </message>
    <message>
        <source>Sun</source>
        <translation>太阳</translation>
    </message>
    <message>
        <source>Phobos</source>
        <translation>火卫一</translation>
    </message>
    <message>
        <source>Deimos</source>
        <translation>火卫二</translation>
    </message>
    <message>
        <source>Io</source>
        <translation>木卫一</translation>
    </message>
    <message>
        <source>Europa</source>
        <translation>木卫二</translation>
    </message>
    <message>
        <source>Ganymede</source>
        <translation>木卫三</translation>
    </message>
    <message>
        <source>Callisto</source>
        <translation>木卫四</translation>
    </message>
    <message>
        <source>Amalthea</source>
        <translation>木卫五</translation>
    </message>
    <message>
        <source>Himalia</source>
        <translation>木卫六</translation>
    </message>
    <message>
        <source>Elara</source>
        <translation>木卫七</translation>
    </message>
    <message>
        <source>Pasiphae</source>
        <translation>木卫八</translation>
    </message>
    <message>
        <source>Sinope</source>
        <translation>木卫九</translation>
    </message>
    <message>
        <source>Lysithea</source>
        <translation>木卫十</translation>
    </message>
    <message>
        <source>Carme</source>
        <translation>木卫十一</translation>
    </message>
    <message>
        <source>Ananke</source>
        <translation>木卫十二</translation>
    </message>
    <message>
        <source>Leda</source>
        <translation>木卫十三</translation>
    </message>
    <message>
        <source>Thebe</source>
        <translation>木卫十四</translation>
    </message>
    <message>
        <source>Adrastea</source>
        <translation>木卫十五</translation>
    </message>
    <message>
        <source>Metis</source>
        <translation>木卫十六</translation>
    </message>
    <message>
        <source>Mimas</source>
        <translation>土卫一</translation>
    </message>
    <message>
        <source>Enceladus</source>
        <translation>土卫二</translation>
    </message>
    <message>
        <source>Tethys</source>
        <translation>土卫三</translation>
    </message>
    <message>
        <source>Dione</source>
        <translation>土卫四</translation>
    </message>
    <message>
        <source>Rhea</source>
        <translation>土卫五</translation>
    </message>
    <message>
        <source>Titan</source>
        <translation>土卫六</translation>
    </message>
    <message>
        <source>Hyperion</source>
        <translation>土卫七</translation>
    </message>
    <message>
        <source>Iapetus</source>
        <translation>土卫八</translation>
    </message>
    <message>
        <source>Phoebe</source>
        <translation>土卫九</translation>
    </message>
    <message>
        <source>Janus</source>
        <translation>土卫十</translation>
    </message>
    <message>
        <source>Epimetheus</source>
        <translation>土卫十一</translation>
    </message>
    <message>
        <source>Helene</source>
        <translation>土卫十二</translation>
    </message>
    <message>
        <source>Telesto</source>
        <translation>土卫十三</translation>
    </message>
    <message>
        <source>Calypso</source>
        <translation>土卫十四</translation>
    </message>
    <message>
        <source>Atlas</source>
        <translation>土卫十五</translation>
    </message>
    <message>
        <source>Prometheus</source>
        <translation>土卫十六</translation>
    </message>
    <message>
        <source>Pandora</source>
        <translation>土卫十七</translation>
    </message>
    <message>
        <source>Pan</source>
        <translation>土卫十八</translation>
    </message>
    <message>
        <source>Methone</source>
        <translation>土卫三十二</translation>
    </message>
    <message>
        <source>Pallene</source>
        <translation>土卫三十三</translation>
    </message>
    <message>
        <source>Polydeuces</source>
        <translation>土卫三十四</translation>
    </message>
    <message>
        <source>Daphnis</source>
        <translation>土卫三十五</translation>
    </message>
    <message>
        <source>Anthe</source>
        <translation>土卫四十九</translation>
    </message>
    <message>
        <source>Aegaeon</source>
        <translation>土卫五十三</translation>
    </message>
    <message>
        <source>Ariel</source>
        <translation>天卫一</translation>
    </message>
    <message>
        <source>Umbriel</source>
        <translation>天卫二</translation>
    </message>
    <message>
        <source>Titania</source>
        <translation>天卫三</translation>
    </message>
    <message>
        <source>Oberon</source>
        <translation>天卫四</translation>
    </message>
    <message>
        <source>Miranda</source>
        <translation>天卫五</translation>
    </message>
    <message>
        <source>Cordelia</source>
        <translation>天卫六</translation>
    </message>
    <message>
        <source>Ophelia</source>
        <translation>天卫七</translation>
    </message>
    <message>
        <source>Bianca</source>
        <translation>天卫八</translation>
    </message>
    <message>
        <source>Cressida</source>
        <translation>天卫九</translation>
    </message>
    <message>
        <source>Desdemona</source>
        <translation>天卫十</translation>
    </message>
    <message>
        <source>Juliet</source>
        <translation>天卫十一</translation>
    </message>
    <message>
        <source>Portia</source>
        <translation>天卫十二</translation>
    </message>
    <message>
        <source>Rosalind</source>
        <translation>天卫十三</translation>
    </message>
    <message>
        <source>Belinda</source>
        <translation>天卫十四</translation>
    </message>
    <message>
        <source>Puck</source>
        <translation>天卫十五</translation>
    </message>
    <message>
        <source>Triton</source>
        <translation>海卫一</translation>
    </message>
    <message>
        <source>Nereid</source>
        <translation>海卫二</translation>
    </message>
    <message>
        <source>Naiad</source>
        <translation>海卫三</translation>
    </message>
    <message>
        <source>Thalassa</source>
        <translation>海卫四</translation>
    </message>
    <message>
        <source>Despina</source>
        <translation>海卫五</translation>
    </message>
    <message>
        <source>Galatea</source>
        <translation>海卫六</translation>
    </message>
    <message>
        <source>Larissa</source>
        <translation>海卫七</translation>
    </message>
    <message>
        <source>Proteus</source>
        <translation>海卫八</translation>
    </message>
    <message>
        <source>Charon</source>
        <translation>冥卫一</translation>
    </message>
    <message>
        <source>MercuryBarycenter</source>
        <translation>水星系质心</translation>
    </message>
    <message>
        <source>VenusBarycenter</source>
        <translation>金星系质心</translation>
    </message>
    <message>
        <source>MarsBarycenter</source>
        <translation>火星系质心</translation>
    </message>
    <message>
        <source>JupiterBarycenter</source>
        <translation>木星系质心</translation>
    </message>
    <message>
        <source>SaturnBarycenter</source>
        <translation>土星系质心</translation>
    </message>
    <message>
        <source>UranusBarycenter</source>
        <translation>天王星系质心</translation>
    </message>
    <message>
        <source>NeptuneBarycenter</source>
        <translation>海王星系质心</translation>
    </message>
    <message>
        <source>PlutoBarycenter</source>
        <translation>冥王星系质心</translation>
    </message>
</context>
<context>
    <name>SolarSystem</name>
    <message>
        <source>SolarSystem</source>
        <translation>太阳系</translation>
    </message>
</context>
</TS>
