target("AstGUI")
    add_rules("ast.qt.shared")
    add_files("**.cpp")
    add_files("**.hpp")
    add_files("**.ts")
    -- add_files("../../data/*.qrc")
    -- add_files("**.ui")
    add_headerfiles("**.hpp", {prefixdir="AstGUI"})
    add_deps("AstUtil", "AstSim", "AstCore", "AstMath", "AstAnalyzer", "AstLoader")
    add_defines("AST_BUILD_LIB_GUI")
    set_default(false)
    if not has_package("qt5widgets") and not is_plat("wasm") then
        set_enabled(false)
    end
    -- set_warnings("more")
